### ISSUE TITLE
编译命令

### ISSUE THREAD

**Issue by bb33bb** [joaovarelas/Obfuscator-LLVM-16.0#1]
我测试了下没测出混淆效果。弱弱的问下楼主，如何编译，用什么参数可以达到混淆效果

**Comment by joaovarelas** [comment]
> 我测试了下没测出混淆效果。弱弱的问下楼主，如何编译，用什么参数可以达到混淆效果

You have build Rust compiler using modified LLVM (OLLVM). When you build `rustc` and `cargo` you should select the appropriate toolchain to use OLLVM when compiling rust binaries. 

Original Post:

- [https://vrls.ws/posts/2023/06/obfuscating-rust-binaries-using-llvm-obfuscator-ollvm/](https://vrls.ws/posts/2023/06/obfuscating-rust-binaries-using-llvm-obfuscator-ollvm/)
- [https://bbs.kanxue.com/thread-274453.htm](https://bbs.kanxue.com/thread-274453.htm)

**Comment by bb33bb** [comment]
> > 我测试了下没测出混淆效果。弱弱的问下楼主，如何编译，用什么参数可以达到混淆效果
> 
> You have build Rust compiler using patched rust-fork of LLVM. When you build `rustc` and `cargo` you should select the appropriate toolchain to use OLLVM when compiling rust binaries.
> 
> Original Post:
> 
> * https://vrls.ws/posts/2023/06/obfuscating-rust-binaries-using-llvm-obfuscator-ollvm/
> * https://bbs.kanxue.com/thread-274453.htm

Thanks!!
